apiVersion: apps/v1
kind: Deployment
metadata:
  name: ohyes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ohyes
  template:
    metadata:
      labels:
        app: ohyes
    spec:
      containers:
      - image: okteto.dev/ohyes:latest
        name: ohyes
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mikuta.nu"
        - name: Vless_UUID
          value: "6b23ed38-03bd-488d-b5bd-f92e77a5631c"
        - name: Vless_Path
          value: "/ohyess"
        - name: Vmess_UUID
          value: "6b23ed38-03bd-488d-b5bd-f92e77a5631c"
        - name: Vmess_Path
          value: "/ohmess"
        - name: Share_Path
          value: "/share233"
