apiVersion: v1
kind: Service
metadata:
  name: ohyes1
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "ohyes1"
    port: 8080
  selector:
    app: ohyes1
